#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.1.2 effective-5.10 (swiftlang-6.1.2.1.2 clang-1700.0.13.5)
#ifndef TAPONLINEBATTLESDK_SWIFT_H
#define TAPONLINEBATTLESDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="TapOnlineBattleSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class NSString;
@class ErrorResponse;
/// 连接回调监听器
SWIFT_PROTOCOL("_TtP18TapOnlineBattleSDK15ConnectListener_")
@protocol ConnectListener
/// 连接成功回调
/// \param playerId 玩家ID
///
- (void)onSuccessWithPlayerId:(NSString * _Nonnull)playerId;
/// 连接失败回调
- (void)onFailureWithError:(ErrorResponse * _Nonnull)error;
@end

@class RoomConfig;
@class PlayerConfig;
/// 创建房间请求配置（对齐 Unity CreateRoomConfig）
SWIFT_CLASS("_TtC18TapOnlineBattleSDK16CreateRoomConfig")
@interface CreateRoomConfig : NSObject
/// 房间配置，必填
@property (nonatomic, readonly, strong) RoomConfig * _Nonnull roomConfig;
/// 玩家配置，选填
@property (nonatomic, readonly, strong) PlayerConfig * _Nonnull playerConfig;
- (nonnull instancetype)initWithRoomConfig:(RoomConfig * _Nonnull)roomConfig playerConfig:(PlayerConfig * _Nonnull)playerConfig OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class RoomInfo;
/// 创建房间回调监听器
SWIFT_PROTOCOL("_TtP18TapOnlineBattleSDK18CreateRoomListener_")
@protocol CreateRoomListener
/// 创建房间成功回调
/// \param roomInfo 房间信息
///
- (void)onSuccessWithRoomInfo:(RoomInfo * _Nonnull)roomInfo;
- (void)onFailureWithError:(ErrorResponse * _Nonnull)error;
@end

/// 断开连接回调监听器
SWIFT_PROTOCOL("_TtP18TapOnlineBattleSDK18DisconnectListener_")
@protocol DisconnectListener
- (void)onSuccess;
- (void)onFailureWithError:(ErrorResponse * _Nonnull)error;
@end

/// 错误码枚举（保留作兼容，值与 TapOnlineBattleConstant 一一对应）
typedef SWIFT_ENUM(NSInteger, ErrorCode, open) {
  ErrorCodeErrorNotLogin = 101,
  ErrorCodeErrorSystemError = 1,
  ErrorCodeErrorSDKError = 2,
  ErrorCodeErrorRequestRateLimitExceeded = 3,
  ErrorCodeErrorMaliciousUser = 4,
  ErrorCodeErrorTooManyConnections = 5,
  ErrorCodeErrorNetworkError = 6,
  ErrorCodeErrorInvalidRequest = 11,
  ErrorCodeErrorInvalidAuthorization = 12,
  ErrorCodeErrorUnauthorized = 13,
  ErrorCodeErrorAlreadySignedIn = 14,
  ErrorCodeErrorPreviousRequestInProgress = 15,
  ErrorCodeErrorUnimplemented = 16,
  ErrorCodeErrorForbidden = 17,
  ErrorCodeErrorRoomTemplateNotFound = 18,
  ErrorCodeErrorRoomCountLimitExceeded = 19,
  ErrorCodeErrorNotInRoom = 20,
  ErrorCodeErrorAlreadyInRoom = 21,
  ErrorCodeErrorNotRoomOwner = 22,
  ErrorCodeErrorRoomFull = 23,
  ErrorCodeErrorRoomNotExist = 24,
  ErrorCodeErrorBattleNotStarted = 25,
  ErrorCodeErrorBattleAlreadyStarted = 26,
  ErrorCodeErrorBattleFrameDataSizeLimitExceeded = 28,
  ErrorCodeErrorBattleFrameDataCountLimitExceeded = 29,
  ErrorCodeErrorPlayerNotFound = 30,
};

/// 错误响应
SWIFT_CLASS("_TtC18TapOnlineBattleSDK13ErrorResponse")
@interface ErrorResponse : NSObject
@property (nonatomic, readonly) NSInteger code;
@property (nonatomic, readonly, copy) NSString * _Nonnull msg;
- (nonnull instancetype)initWithCode:(NSInteger)code msg:(NSString * _Nonnull)msg OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class PlayerInputInfo;
/// 帧同步数据（对齐 Unity FrameData）
SWIFT_CLASS("_TtC18TapOnlineBattleSDK9FrameData")
@interface FrameData : NSObject
/// 帧ID，从1开始递增
@property (nonatomic, readonly) NSInteger id;
/// 当前帧的所有玩家操作，按服务端接收时间排序
@property (nonatomic, readonly, copy) NSArray<PlayerInputInfo *> * _Nonnull inputs;
- (nonnull instancetype)initWithId:(NSInteger)id inputs:(NSArray<PlayerInputInfo *> * _Nonnull)inputs OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// 开始对战时返回的对战信息（对齐 Unity FrameSyncInfo）
SWIFT_CLASS("_TtC18TapOnlineBattleSDK13FrameSyncInfo")
@interface FrameSyncInfo : NSObject
/// 房间信息
@property (nonatomic, readonly, strong) RoomInfo * _Nonnull roomInfo;
/// 帧同步ID，房间内唯一，房间内每次开始帧同步都会变化
@property (nonatomic, readonly) NSInteger frameSyncId;
/// 用于初始化线性同余伪随机数生成器的随机数种子
@property (nonatomic, readonly) NSInteger seed;
/// 对战开始的服务端时间，1970年开始的毫秒数（JSON key: serverTms）
@property (nonatomic, readonly, copy) NSString * _Nonnull serverTime;
- (nonnull instancetype)initWithRoomInfo:(RoomInfo * _Nonnull)roomInfo frameSyncId:(NSInteger)frameSyncId seed:(NSInteger)seed serverTime:(NSString * _Nonnull)serverTime OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class RoomListData;
/// 获取房间列表回调监听器
SWIFT_PROTOCOL("_TtP18TapOnlineBattleSDK19GetRoomListListener_")
@protocol GetRoomListListener
/// 获取房间列表成功回调
/// \param data 房间列表数据
///
- (void)onSuccessWithData:(RoomListData * _Nonnull)data;
- (void)onFailureWithError:(ErrorResponse * _Nonnull)error;
@end

/// 加入房间回调监听器
SWIFT_PROTOCOL("_TtP18TapOnlineBattleSDK16JoinRoomListener_")
@protocol JoinRoomListener
/// 加入房间成功回调
/// \param roomInfo 房间信息
///
- (void)onSuccessWithRoomInfo:(RoomInfo * _Nonnull)roomInfo;
- (void)onFailureWithError:(ErrorResponse * _Nonnull)error;
@end

/// 踢出房间玩家回调监听器
SWIFT_PROTOCOL("_TtP18TapOnlineBattleSDK22KickRoomPlayerListener_")
@protocol KickRoomPlayerListener
- (void)onSuccess;
- (void)onFailureWithError:(ErrorResponse * _Nonnull)error;
@end

/// 离开房间回调监听器
SWIFT_PROTOCOL("_TtP18TapOnlineBattleSDK17LeaveRoomListener_")
@protocol LeaveRoomListener
- (void)onSuccess;
- (void)onFailureWithError:(ErrorResponse * _Nonnull)error;
@end

/// 匹配房间请求配置（对齐 Unity MatchRoomConfig）
SWIFT_CLASS("_TtC18TapOnlineBattleSDK15MatchRoomConfig")
@interface MatchRoomConfig : NSObject
/// 房间配置，必填
@property (nonatomic, readonly, strong) RoomConfig * _Nonnull roomConfig;
/// 玩家配置，选填
@property (nonatomic, readonly, strong) PlayerConfig * _Nonnull playerConfig;
- (nonnull instancetype)initWithRoomConfig:(RoomConfig * _Nonnull)roomConfig playerConfig:(PlayerConfig * _Nonnull)playerConfig OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// 匹配房间回调监听器
SWIFT_PROTOCOL("_TtP18TapOnlineBattleSDK17MatchRoomListener_")
@protocol MatchRoomListener
/// 匹配房间成功回调
/// \param roomInfo 房间信息
///
- (void)onSuccessWithRoomInfo:(RoomInfo * _Nonnull)roomInfo;
- (void)onFailureWithError:(ErrorResponse * _Nonnull)error;
@end

/// 玩家配置
SWIFT_CLASS("_TtC18TapOnlineBattleSDK12PlayerConfig")
@interface PlayerConfig : NSObject
/// 自定义玩家状态，整形，选填。开发者可随意设置任何值，意义由开发者自行判断
@property (nonatomic, readonly) NSInteger customStatus;
/// 自定义玩家属性，选填。开发者可以随意设置任何数据，最大长度为2048字节
@property (nonatomic, readonly, copy) NSString * _Nonnull customProperties;
- (nonnull instancetype)initWithCustomStatus:(NSInteger)customStatus customProperties:(NSString * _Nonnull)customProperties OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// 玩家信息
SWIFT_CLASS("_TtC18TapOnlineBattleSDK10PlayerInfo")
@interface PlayerInfo : NSObject
/// 玩家ID
@property (nonatomic, readonly, copy) NSString * _Nonnull id;
/// 玩家状态：0-离线、1-在线
@property (nonatomic, readonly) NSInteger status;
/// 自定义玩家状态，开发者可随意设置任何值，意义由开发者自行判断，选填
@property (nonatomic, readonly) NSInteger customStatus;
/// 自定义玩家属性，选填
@property (nonatomic, readonly, copy) NSString * _Nonnull customProperties;
- (nonnull instancetype)initWithId:(NSString * _Nonnull)id status:(NSInteger)status customStatus:(NSInteger)customStatus customProperties:(NSString * _Nonnull)customProperties OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// 用户操作信息（对齐 Unity PlayerInputInfo）
SWIFT_CLASS("_TtC18TapOnlineBattleSDK15PlayerInputInfo")
@interface PlayerInputInfo : NSObject
/// 玩家ID
@property (nonatomic, readonly, copy) NSString * _Nonnull playerId;
/// 玩家操作数据，utf8字符串格式
@property (nonatomic, readonly, copy) NSString * _Nonnull data;
/// 服务器收到该操作数据的时间，1970年开始的毫秒数（JSON key: serverTms）
@property (nonatomic, readonly, copy) NSString * _Nonnull serverTime;
- (nonnull instancetype)initWithPlayerId:(NSString * _Nonnull)playerId data:(NSString * _Nonnull)data serverTime:(NSString * _Nonnull)serverTime OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// 随机数生成器对象（对齐 Unity RandomNumberGenerator）
SWIFT_CLASS("_TtC18TapOnlineBattleSDK21RandomNumberGenerator")
@interface RandomNumberGenerator : NSObject
/// 使用指定种子创建（使用 onFrameSyncStarted 返回的 seed）
- (nonnull instancetype)initWithSeed:(NSInteger)seed OBJC_DESIGNATED_INITIALIZER;
/// 生成 0 ~ 0x7fffffff 之间的随机整数
- (NSInteger)randomInt SWIFT_WARN_UNUSED_RESULT;
/// 释放 native 资源（使用完毕后必须调用；deinit 兜底自动释放）
- (void)free;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// 房间基本信息（用于房间列表）
SWIFT_CLASS("_TtC18TapOnlineBattleSDK13RoomBasicInfo")
@interface RoomBasicInfo : NSObject
/// 房间ID
@property (nonatomic, readonly, copy) NSString * _Nonnull id;
/// 房间名字，选填
@property (nonatomic, readonly, copy) NSString * _Nonnull name;
/// 房间类型
@property (nonatomic, readonly, copy) NSString * _Nonnull type;
/// 房间自定义属性
@property (nonatomic, readonly, copy) NSString * _Nonnull customProperties;
/// 房间最大人数
@property (nonatomic, readonly) NSInteger maxPlayerCount;
/// 房间当前人数
@property (nonatomic, readonly) NSInteger playerCount;
/// 房间创建时间
@property (nonatomic, readonly, copy) NSString * _Nonnull createTime;
- (nonnull instancetype)initWithId:(NSString * _Nonnull)id name:(NSString * _Nonnull)name type:(NSString * _Nonnull)type customProperties:(NSString * _Nonnull)customProperties maxPlayerCount:(NSInteger)maxPlayerCount playerCount:(NSInteger)playerCount createTime:(NSString * _Nonnull)createTime OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// 房间配置
SWIFT_CLASS("_TtC18TapOnlineBattleSDK10RoomConfig")
@interface RoomConfig : NSObject
/// 房间最大支持人数，取值范围为[1, 20]，必填
@property (nonatomic, readonly) NSInteger maxPlayerCount;
/// 房间类型，最大32字节,必填
@property (nonatomic, readonly, copy) NSString * _Nonnull type;
/// 房间匹配参数，选填，最大支持3个K/V对
@property (nonatomic, readonly, copy) NSDictionary<NSString *, NSString *> * _Nonnull matchParams;
/// 房间名称，最大64个字节，选填
@property (nonatomic, readonly, copy) NSString * _Nonnull name;
/// 自定义房间属性，最大2048字节，选填
@property (nonatomic, readonly, copy) NSString * _Nonnull customProperties;
- (nonnull instancetype)initWithMaxPlayerCount:(NSInteger)maxPlayerCount type:(NSString * _Nonnull)type matchParams:(NSDictionary<NSString *, NSString *> * _Nonnull)matchParams name:(NSString * _Nonnull)name customProperties:(NSString * _Nonnull)customProperties OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// 房间信息
SWIFT_CLASS("_TtC18TapOnlineBattleSDK8RoomInfo")
@interface RoomInfo : NSObject
/// 房间ID
@property (nonatomic, readonly, copy) NSString * _Nonnull id;
/// 房间名称，选填
@property (nonatomic, readonly, copy) NSString * _Nonnull name;
/// 房间类型
@property (nonatomic, readonly, copy) NSString * _Nonnull type;
/// 房主ID
@property (nonatomic, readonly, copy) NSString * _Nonnull ownerId;
/// 房间状态，0-未开始，1-进行中（帧同步中），2-已结束，选填
@property (nonatomic, readonly) NSInteger status;
/// 自定义房间属性，选填
@property (nonatomic, readonly, copy) NSString * _Nonnull customProperties;
/// 房间最大支持人数
@property (nonatomic, readonly) NSInteger maxPlayerCount;
/// 房间内当前玩家列表
@property (nonatomic, readonly, copy) NSArray<PlayerInfo *> * _Nonnull players;
/// 房间创建时间，1970年开始的秒数
@property (nonatomic, readonly, copy) NSString * _Nonnull createTime;
- (nonnull instancetype)initWithId:(NSString * _Nonnull)id name:(NSString * _Nonnull)name type:(NSString * _Nonnull)type ownerId:(NSString * _Nonnull)ownerId status:(NSInteger)status customProperties:(NSString * _Nonnull)customProperties maxPlayerCount:(NSInteger)maxPlayerCount players:(NSArray<PlayerInfo *> * _Nonnull)players createTime:(NSString * _Nonnull)createTime OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// 查询房间返回结果（对齐 Unity RoomListData）
SWIFT_CLASS("_TtC18TapOnlineBattleSDK12RoomListData")
@interface RoomListData : NSObject
/// 房间列表
@property (nonatomic, readonly, copy) NSArray<RoomBasicInfo *> * _Nonnull rooms;
/// 用于请求下一页的偏移量
@property (nonatomic, readonly) NSInteger offset;
/// 是否还有更多房间可以拉取
@property (nonatomic, readonly) BOOL hasMore;
- (nonnull instancetype)initWithRooms:(NSArray<RoomBasicInfo *> * _Nonnull)rooms offset:(NSInteger)offset hasMore:(BOOL)hasMore OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// 发送自定义消息回调监听器
SWIFT_PROTOCOL("_TtP18TapOnlineBattleSDK25SendCustomMessageListener_")
@protocol SendCustomMessageListener
- (void)onSuccess;
- (void)onFailureWithError:(ErrorResponse * _Nonnull)error;
@end

/// 发送帧输入回调监听器
SWIFT_PROTOCOL("_TtP18TapOnlineBattleSDK22SendFrameInputListener_")
@protocol SendFrameInputListener
- (void)onSuccess;
- (void)onFailureWithError:(ErrorResponse * _Nonnull)error;
@end

/// 开始帧同步回调监听器
SWIFT_PROTOCOL("_TtP18TapOnlineBattleSDK22StartFrameSyncListener_")
@protocol StartFrameSyncListener
- (void)onSuccess;
- (void)onFailureWithError:(ErrorResponse * _Nonnull)error;
@end

/// 停止帧同步回调监听器
SWIFT_PROTOCOL("_TtP18TapOnlineBattleSDK21StopFrameSyncListener_")
@protocol StopFrameSyncListener
- (void)onSuccess;
- (void)onFailureWithError:(ErrorResponse * _Nonnull)error;
@end

/// 对战通知监听器（对齐 Unity TapOnlineBattleCallback，方法签名改为散字段参数）
/// ⚠️ 线程说明：请求回调和通知回调均在 com.taptap.battle.callback 串行队列执行，
/// 不保证主线程。如需更新 UI，请主动派发到 DispatchQueue.main。
SWIFT_PROTOCOL("_TtP18TapOnlineBattleSDK23TapOnlineBattleCallback_")
@protocol TapOnlineBattleCallback <NSObject>
@optional
/// 与服务端连接断开
- (void)onDisconnectedWithCode:(NSInteger)code msg:(NSString * _Nonnull)msg;
/// 对战服务端异常
- (void)onBattleServiceError;
/// 房间属性变更
- (void)onRoomPropertiesChangedWithId:(NSString * _Nonnull)id name:(NSString * _Nonnull)name customProperties:(NSString * _Nonnull)customProperties;
/// 玩家更新自定义属性
- (void)onPlayerCustomPropertiesChangedWithPlayerId:(NSString * _Nonnull)playerId properties:(NSString * _Nonnull)properties;
/// 玩家更新自定义状态
- (void)onPlayerCustomStatusChangedWithPlayerId:(NSString * _Nonnull)playerId status:(NSInteger)status;
/// 开始帧同步
- (void)onFrameSyncStartedWithFrameSyncInfo:(FrameSyncInfo * _Nonnull)frameSyncInfo;
/// 收到帧同步数据
- (void)onFrameReceivedWithFrameData:(FrameData * _Nonnull)frameData;
/// 停止帧同步
- (void)onFrameSyncStoppedWithRoomId:(NSString * _Nonnull)roomId frameSyncId:(NSInteger)frameSyncId reason:(NSInteger)reason;
/// 玩家离线
- (void)onPlayerOfflineWithRoomId:(NSString * _Nonnull)roomId roomOwnerId:(NSString * _Nonnull)roomOwnerId playerId:(NSString * _Nonnull)playerId;
/// 玩家离开房间
- (void)onPlayerLeftWithRoomId:(NSString * _Nonnull)roomId roomOwnerId:(NSString * _Nonnull)roomOwnerId playerId:(NSString * _Nonnull)playerId;
/// 玩家进入房间
- (void)onPlayerEnteredWithRoomId:(NSString * _Nonnull)roomId playerInfo:(PlayerInfo * _Nonnull)playerInfo;
/// 收到玩家自定义消息
- (void)onCustomMessageReceivedWithPlayerId:(NSString * _Nonnull)playerId msg:(NSString * _Nonnull)msg;
/// 玩家被踢出
- (void)onPlayerKickedWithRoomId:(NSString * _Nonnull)roomId playerId:(NSString * _Nonnull)playerId;
@end

/// 错误码常量（对齐 Unity TapOnlineBattleConstant）
SWIFT_CLASS("_TtC18TapOnlineBattleSDK23TapOnlineBattleConstant")
@interface TapOnlineBattleConstant : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ERROR_INVALID_PARAMS;)
+ (NSInteger)ERROR_INVALID_PARAMS SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ERROR_INIT_INTERNAL_FAILED;)
+ (NSInteger)ERROR_INIT_INTERNAL_FAILED SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ERROR_UNKNOWN;)
+ (NSInteger)ERROR_UNKNOWN SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ERROR_NOT_INIT_OR_LOGIN;)
+ (NSInteger)ERROR_NOT_INIT_OR_LOGIN SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ERROR_NOT_LAUNCHED_BY_TAP_CLIENT;)
+ (NSInteger)ERROR_NOT_LAUNCHED_BY_TAP_CLIENT SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ERROR_SYSTEM_ERROR;)
+ (NSInteger)ERROR_SYSTEM_ERROR SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ERROR_SDK_ERROR;)
+ (NSInteger)ERROR_SDK_ERROR SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ERROR_REQUEST_RATE_LIMIT_EXCEEDED;)
+ (NSInteger)ERROR_REQUEST_RATE_LIMIT_EXCEEDED SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ERROR_MALICIOUS_USER;)
+ (NSInteger)ERROR_MALICIOUS_USER SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ERROR_TOO_MANY_CONNECTIONS;)
+ (NSInteger)ERROR_TOO_MANY_CONNECTIONS SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ERROR_NETWORK_ERROR;)
+ (NSInteger)ERROR_NETWORK_ERROR SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ERROR_INVALID_REQUEST;)
+ (NSInteger)ERROR_INVALID_REQUEST SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ERROR_INVALID_AUTHORIZATION;)
+ (NSInteger)ERROR_INVALID_AUTHORIZATION SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ERROR_UNAUTHORIZED;)
+ (NSInteger)ERROR_UNAUTHORIZED SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ERROR_ALREADY_CONNECTED;)
+ (NSInteger)ERROR_ALREADY_CONNECTED SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ERROR_PREVIOUS_REQUEST_IN_PROGRESS;)
+ (NSInteger)ERROR_PREVIOUS_REQUEST_IN_PROGRESS SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ERROR_UNIMPLEMENTED;)
+ (NSInteger)ERROR_UNIMPLEMENTED SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ERROR_FORBIDDEN;)
+ (NSInteger)ERROR_FORBIDDEN SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ERROR_ROOM_TEMPLATE_NOT_FOUND;)
+ (NSInteger)ERROR_ROOM_TEMPLATE_NOT_FOUND SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ERROR_ROOM_COUNT_LIMIT_EXCEEDED;)
+ (NSInteger)ERROR_ROOM_COUNT_LIMIT_EXCEEDED SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ERROR_NOT_IN_ROOM;)
+ (NSInteger)ERROR_NOT_IN_ROOM SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ERROR_ALREADY_IN_ROOM;)
+ (NSInteger)ERROR_ALREADY_IN_ROOM SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ERROR_NOT_ROOM_OWNER;)
+ (NSInteger)ERROR_NOT_ROOM_OWNER SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ERROR_ROOM_FULL;)
+ (NSInteger)ERROR_ROOM_FULL SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ERROR_ROOM_NOT_EXIST;)
+ (NSInteger)ERROR_ROOM_NOT_EXIST SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ERROR_FRAME_SYNC_NOT_STARTED;)
+ (NSInteger)ERROR_FRAME_SYNC_NOT_STARTED SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ERROR_FRAME_SYNC_ALREADY_STARTED;)
+ (NSInteger)ERROR_FRAME_SYNC_ALREADY_STARTED SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ERROR_FRAME_INPUT_SIZE_LIMIT_EXCEEDED;)
+ (NSInteger)ERROR_FRAME_INPUT_SIZE_LIMIT_EXCEEDED SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ERROR_FRAME_INPUT_COUNT_LIMIT_EXCEEDED;)
+ (NSInteger)ERROR_FRAME_INPUT_COUNT_LIMIT_EXCEEDED SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ERROR_PLAYER_NOT_FOUND;)
+ (NSInteger)ERROR_PLAYER_NOT_FOUND SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// @deprecated 请迁移至 TapTapOnlineBattle
/// 本类保留用于源码级兼容，所有方法转发至 TapTapOnlineBattle。
SWIFT_CLASS_NAMED("TapTapBattleLegacy") SWIFT_DEPRECATED_MSG("请迁移至 TapTapOnlineBattle", "_TtC18TapOnlineBattleSDK18TapTapOnlineBattle")
@interface TapTapBattle : NSObject
+ (void)connectWithListener:(id <ConnectListener> _Nullable)listener SWIFT_DEPRECATED_MSG("", "TapTapOnlineBattle.connect");
+ (void)disconnectWithListener:(id <DisconnectListener> _Nullable)listener SWIFT_DEPRECATED_MSG("", "TapTapOnlineBattle.disconnect");
+ (void)createRoomWithRequest:(CreateRoomConfig * _Nonnull)request listener:(id <CreateRoomListener> _Nullable)listener SWIFT_DEPRECATED_MSG("", "TapTapOnlineBattle.createRoom");
+ (void)matchRoomWithRequest:(MatchRoomConfig * _Nonnull)request listener:(id <MatchRoomListener> _Nullable)listener SWIFT_DEPRECATED_MSG("", "TapTapOnlineBattle.matchRoom");
+ (void)leaveRoomWithListener:(id <LeaveRoomListener> _Nullable)listener SWIFT_DEPRECATED_MSG("", "TapTapOnlineBattle.leaveRoom");
+ (void)startFrameSyncWithListener:(id <StartFrameSyncListener> _Nullable)listener SWIFT_DEPRECATED_MSG("", "TapTapOnlineBattle.startFrameSync");
+ (void)stopFrameSyncWithListener:(id <StopFrameSyncListener> _Nullable)listener SWIFT_DEPRECATED_MSG("", "TapTapOnlineBattle.stopFrameSync");
+ (void)kickRoomPlayerWithPlayerID:(NSString * _Nonnull)playerID listener:(id <KickRoomPlayerListener> _Nullable)listener SWIFT_DEPRECATED_MSG("", "TapTapOnlineBattle.kickRoomPlayer");
+ (void)registerOnlineBattleCallback:(id <TapOnlineBattleCallback> _Nonnull)listener SWIFT_DEPRECATED_MSG("", "TapTapOnlineBattle.registerOnlineBattleCallback");
+ (void)unRegisterOnlineBattleCallback:(id <TapOnlineBattleCallback> _Nonnull)listener SWIFT_DEPRECATED_MSG("", "TapTapOnlineBattle.unRegisterOnlineBattleCallback");
+ (RandomNumberGenerator * _Nonnull)NewRandomNumberGeneratorWithSeed:(NSInteger)seed SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_MSG("", "TapTapOnlineBattle.NewRandomNumberGenerator");
+ (void)setLogLevelWithLevel:(NSInteger)level logToConsole:(BOOL)logToConsole SWIFT_DEPRECATED_MSG("", "TapTapOnlineBattle.setLogLevel");
+ (NSString * _Nullable)getVersion SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_MSG("", "TapTapOnlineBattle.getVersion");
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@protocol UpdatePlayerCustomStatusListener;
@protocol UpdatePlayerCustomPropertiesListener;
@protocol UpdateRoomPropertiesListener;
/// TapTap Battle SDK Public API
/// 提供对战服务功能，包括房间管理、帧同步对战等。
/// Native 库 (onlinebattle_sdk.xcframework) 在 TapSDK 初始化时自动加载。
SWIFT_CLASS("_TtC18TapOnlineBattleSDK18TapTapOnlineBattle")
@interface TapTapOnlineBattle : NSObject
/// SDK 包装层版本（由 CI bump 流程统一维护，与 podspec 版本对齐）
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull Version;)
+ (NSString * _Nonnull)Version SWIFT_WARN_UNUSED_RESULT;
+ (void)connectWithListener:(id <ConnectListener> _Nullable)listener;
+ (void)disconnectWithListener:(id <DisconnectListener> _Nullable)listener;
/// 创建房间
+ (void)createRoomWithRequest:(CreateRoomConfig * _Nonnull)request listener:(id <CreateRoomListener> _Nullable)listener;
/// 匹配房间（匹配不到时自动创建）
+ (void)matchRoomWithRequest:(MatchRoomConfig * _Nonnull)request listener:(id <MatchRoomListener> _Nullable)listener;
/// 获取房间列表
/// \param roomType 房间类型，不填则拉取全部类型
///
/// \param offset 偏移量，默认为 0
///
/// \param limit 获取数量，默认为 20，最大 100
///
+ (void)getRoomListWithRoomType:(NSString * _Nonnull)roomType offset:(NSInteger)offset limit:(NSInteger)limit listener:(id <GetRoomListListener> _Nullable)listener;
/// 加入房间
/// \param roomId 房间ID
///
/// \param playerConfig 玩家配置，选填
///
+ (void)joinRoomWithRoomId:(NSString * _Nonnull)roomId playerConfig:(PlayerConfig * _Nonnull)playerConfig listener:(id <JoinRoomListener> _Nullable)listener;
/// 离开房间
+ (void)leaveRoomWithListener:(id <LeaveRoomListener> _Nullable)listener;
/// 更新玩家自定义状态
+ (void)updatePlayerCustomStatusWithStatus:(NSInteger)status listener:(id <UpdatePlayerCustomStatusListener> _Nullable)listener;
/// 更新玩家自定义属性
+ (void)updatePlayerCustomPropertiesWithProperties:(NSString * _Nonnull)properties listener:(id <UpdatePlayerCustomPropertiesListener> _Nullable)listener;
/// 更新房间属性（仅限房主调用）
/// \param roomName 房间名称
///
/// \param properties 房间自定义属性，最大 2048 字节
///
+ (void)updateRoomPropertiesWithRoomName:(NSString * _Nonnull)roomName properties:(NSString * _Nonnull)properties listener:(id <UpdateRoomPropertiesListener> _Nullable)listener;
+ (void)startFrameSyncWithListener:(id <StartFrameSyncListener> _Nullable)listener;
/// 发送玩家帧输入，同一帧允许发送多次操作，无需等待回调
/// \param data 游戏操作，utf8字符串格式，最大 1024 字节
///
+ (void)sendFrameInputWithData:(NSString * _Nonnull)data listener:(id <SendFrameInputListener> _Nullable)listener;
+ (void)stopFrameSyncWithListener:(id <StopFrameSyncListener> _Nullable)listener;
+ (void)kickRoomPlayerWithPlayerID:(NSString * _Nonnull)playerID listener:(id <KickRoomPlayerListener> _Nullable)listener;
/// 发送自定义消息，每秒允许调用 20 次，无需等待回调
/// \param msg 消息内容，utf8字符串，最大 2048 字节
///
/// \param type 接收者类型：0 房间所有玩家（不含发送者），1 指定玩家
///
/// \param receivers type==1 时有效，最多 20 个ID
///
+ (void)sendCustomMessageWithMsg:(NSString * _Nonnull)msg type:(NSInteger)type receivers:(NSArray<NSString *> * _Nonnull)receivers listener:(id <SendCustomMessageListener> _Nullable)listener;
/// 创建随机数生成器对象（对齐 Unity NewRandomNumberGenerator）
/// 使用 onFrameSyncStarted 返回的 seed，保证所有玩家随机序列一致
+ (RandomNumberGenerator * _Nonnull)NewRandomNumberGeneratorWithSeed:(NSInteger)seed SWIFT_WARN_UNUSED_RESULT;
+ (void)initializeSDK;
+ (void)setLogLevelWithLevel:(NSInteger)level logToConsole:(BOOL)logToConsole;
+ (NSString * _Nullable)getVersion SWIFT_WARN_UNUSED_RESULT;
/// 注册对战通知监听器
+ (void)registerOnlineBattleCallback:(id <TapOnlineBattleCallback> _Nonnull)listener;
/// 注销对战通知监听器
+ (void)unRegisterOnlineBattleCallback:(id <TapOnlineBattleCallback> _Nonnull)listener;
+ (void)ensureInitialization;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// 更新玩家自定义属性回调监听器
SWIFT_PROTOCOL("_TtP18TapOnlineBattleSDK36UpdatePlayerCustomPropertiesListener_")
@protocol UpdatePlayerCustomPropertiesListener
- (void)onSuccess;
- (void)onFailureWithError:(ErrorResponse * _Nonnull)error;
@end

/// 更新玩家自定义状态回调监听器
SWIFT_PROTOCOL("_TtP18TapOnlineBattleSDK32UpdatePlayerCustomStatusListener_")
@protocol UpdatePlayerCustomStatusListener
- (void)onSuccess;
- (void)onFailureWithError:(ErrorResponse * _Nonnull)error;
@end

/// 更新房间属性回调监听器
SWIFT_PROTOCOL("_TtP18TapOnlineBattleSDK28UpdateRoomPropertiesListener_")
@protocol UpdateRoomPropertiesListener
- (void)onSuccess;
- (void)onFailureWithError:(ErrorResponse * _Nonnull)error;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 6.1.2 effective-5.10 (swiftlang-6.1.2.1.2 clang-1700.0.13.5)
#ifndef TAPONLINEBATTLESDK_SWIFT_H
#define TAPONLINEBATTLESDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="TapOnlineBattleSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class NSString;
@class ErrorResponse;
/// 连接回调监听器
SWIFT_PROTOCOL("_TtP18TapOnlineBattleSDK15ConnectListener_")
@protocol ConnectListener
/// 连接成功回调
/// \param playerId 玩家ID
///
- (void)onSuccessWithPlayerId:(NSString * _Nonnull)playerId;
/// 连接失败回调
- (void)onFailureWithError:(ErrorResponse * _Nonnull)error;
@end

@class RoomConfig;
@class PlayerConfig;
/// 创建房间请求配置（对齐 Unity CreateRoomConfig）
SWIFT_CLASS("_TtC18TapOnlineBattleSDK16CreateRoomConfig")
@interface CreateRoomConfig : NSObject
/// 房间配置，必填
@property (nonatomic, readonly, strong) RoomConfig * _Nonnull roomConfig;
/// 玩家配置，选填
@property (nonatomic, readonly, strong) PlayerConfig * _Nonnull playerConfig;
- (nonnull instancetype)initWithRoomConfig:(RoomConfig * _Nonnull)roomConfig playerConfig:(PlayerConfig * _Nonnull)playerConfig OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class RoomInfo;
/// 创建房间回调监听器
SWIFT_PROTOCOL("_TtP18TapOnlineBattleSDK18CreateRoomListener_")
@protocol CreateRoomListener
/// 创建房间成功回调
/// \param roomInfo 房间信息
///
- (void)onSuccessWithRoomInfo:(RoomInfo * _Nonnull)roomInfo;
- (void)onFailureWithError:(ErrorResponse * _Nonnull)error;
@end

/// 断开连接回调监听器
SWIFT_PROTOCOL("_TtP18TapOnlineBattleSDK18DisconnectListener_")
@protocol DisconnectListener
- (void)onSuccess;
- (void)onFailureWithError:(ErrorResponse * _Nonnull)error;
@end

/// 错误码枚举（保留作兼容，值与 TapOnlineBattleConstant 一一对应）
typedef SWIFT_ENUM(NSInteger, ErrorCode, open) {
  ErrorCodeErrorNotLogin = 101,
  ErrorCodeErrorSystemError = 1,
  ErrorCodeErrorSDKError = 2,
  ErrorCodeErrorRequestRateLimitExceeded = 3,
  ErrorCodeErrorMaliciousUser = 4,
  ErrorCodeErrorTooManyConnections = 5,
  ErrorCodeErrorNetworkError = 6,
  ErrorCodeErrorInvalidRequest = 11,
  ErrorCodeErrorInvalidAuthorization = 12,
  ErrorCodeErrorUnauthorized = 13,
  ErrorCodeErrorAlreadySignedIn = 14,
  ErrorCodeErrorPreviousRequestInProgress = 15,
  ErrorCodeErrorUnimplemented = 16,
  ErrorCodeErrorForbidden = 17,
  ErrorCodeErrorRoomTemplateNotFound = 18,
  ErrorCodeErrorRoomCountLimitExceeded = 19,
  ErrorCodeErrorNotInRoom = 20,
  ErrorCodeErrorAlreadyInRoom = 21,
  ErrorCodeErrorNotRoomOwner = 22,
  ErrorCodeErrorRoomFull = 23,
  ErrorCodeErrorRoomNotExist = 24,
  ErrorCodeErrorBattleNotStarted = 25,
  ErrorCodeErrorBattleAlreadyStarted = 26,
  ErrorCodeErrorBattleFrameDataSizeLimitExceeded = 28,
  ErrorCodeErrorBattleFrameDataCountLimitExceeded = 29,
  ErrorCodeErrorPlayerNotFound = 30,
};

/// 错误响应
SWIFT_CLASS("_TtC18TapOnlineBattleSDK13ErrorResponse")
@interface ErrorResponse : NSObject
@property (nonatomic, readonly) NSInteger code;
@property (nonatomic, readonly, copy) NSString * _Nonnull msg;
- (nonnull instancetype)initWithCode:(NSInteger)code msg:(NSString * _Nonnull)msg OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class PlayerInputInfo;
/// 帧同步数据（对齐 Unity FrameData）
SWIFT_CLASS("_TtC18TapOnlineBattleSDK9FrameData")
@interface FrameData : NSObject
/// 帧ID，从1开始递增
@property (nonatomic, readonly) NSInteger id;
/// 当前帧的所有玩家操作，按服务端接收时间排序
@property (nonatomic, readonly, copy) NSArray<PlayerInputInfo *> * _Nonnull inputs;
- (nonnull instancetype)initWithId:(NSInteger)id inputs:(NSArray<PlayerInputInfo *> * _Nonnull)inputs OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// 开始对战时返回的对战信息（对齐 Unity FrameSyncInfo）
SWIFT_CLASS("_TtC18TapOnlineBattleSDK13FrameSyncInfo")
@interface FrameSyncInfo : NSObject
/// 房间信息
@property (nonatomic, readonly, strong) RoomInfo * _Nonnull roomInfo;
/// 帧同步ID，房间内唯一，房间内每次开始帧同步都会变化
@property (nonatomic, readonly) NSInteger frameSyncId;
/// 用于初始化线性同余伪随机数生成器的随机数种子
@property (nonatomic, readonly) NSInteger seed;
/// 对战开始的服务端时间，1970年开始的毫秒数（JSON key: serverTms）
@property (nonatomic, readonly, copy) NSString * _Nonnull serverTime;
- (nonnull instancetype)initWithRoomInfo:(RoomInfo * _Nonnull)roomInfo frameSyncId:(NSInteger)frameSyncId seed:(NSInteger)seed serverTime:(NSString * _Nonnull)serverTime OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class RoomListData;
/// 获取房间列表回调监听器
SWIFT_PROTOCOL("_TtP18TapOnlineBattleSDK19GetRoomListListener_")
@protocol GetRoomListListener
/// 获取房间列表成功回调
/// \param data 房间列表数据
///
- (void)onSuccessWithData:(RoomListData * _Nonnull)data;
- (void)onFailureWithError:(ErrorResponse * _Nonnull)error;
@end

/// 加入房间回调监听器
SWIFT_PROTOCOL("_TtP18TapOnlineBattleSDK16JoinRoomListener_")
@protocol JoinRoomListener
/// 加入房间成功回调
/// \param roomInfo 房间信息
///
- (void)onSuccessWithRoomInfo:(RoomInfo * _Nonnull)roomInfo;
- (void)onFailureWithError:(ErrorResponse * _Nonnull)error;
@end

/// 踢出房间玩家回调监听器
SWIFT_PROTOCOL("_TtP18TapOnlineBattleSDK22KickRoomPlayerListener_")
@protocol KickRoomPlayerListener
- (void)onSuccess;
- (void)onFailureWithError:(ErrorResponse * _Nonnull)error;
@end

/// 离开房间回调监听器
SWIFT_PROTOCOL("_TtP18TapOnlineBattleSDK17LeaveRoomListener_")
@protocol LeaveRoomListener
- (void)onSuccess;
- (void)onFailureWithError:(ErrorResponse * _Nonnull)error;
@end

/// 匹配房间请求配置（对齐 Unity MatchRoomConfig）
SWIFT_CLASS("_TtC18TapOnlineBattleSDK15MatchRoomConfig")
@interface MatchRoomConfig : NSObject
/// 房间配置，必填
@property (nonatomic, readonly, strong) RoomConfig * _Nonnull roomConfig;
/// 玩家配置，选填
@property (nonatomic, readonly, strong) PlayerConfig * _Nonnull playerConfig;
- (nonnull instancetype)initWithRoomConfig:(RoomConfig * _Nonnull)roomConfig playerConfig:(PlayerConfig * _Nonnull)playerConfig OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// 匹配房间回调监听器
SWIFT_PROTOCOL("_TtP18TapOnlineBattleSDK17MatchRoomListener_")
@protocol MatchRoomListener
/// 匹配房间成功回调
/// \param roomInfo 房间信息
///
- (void)onSuccessWithRoomInfo:(RoomInfo * _Nonnull)roomInfo;
- (void)onFailureWithError:(ErrorResponse * _Nonnull)error;
@end

/// 玩家配置
SWIFT_CLASS("_TtC18TapOnlineBattleSDK12PlayerConfig")
@interface PlayerConfig : NSObject
/// 自定义玩家状态，整形，选填。开发者可随意设置任何值，意义由开发者自行判断
@property (nonatomic, readonly) NSInteger customStatus;
/// 自定义玩家属性，选填。开发者可以随意设置任何数据，最大长度为2048字节
@property (nonatomic, readonly, copy) NSString * _Nonnull customProperties;
- (nonnull instancetype)initWithCustomStatus:(NSInteger)customStatus customProperties:(NSString * _Nonnull)customProperties OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// 玩家信息
SWIFT_CLASS("_TtC18TapOnlineBattleSDK10PlayerInfo")
@interface PlayerInfo : NSObject
/// 玩家ID
@property (nonatomic, readonly, copy) NSString * _Nonnull id;
/// 玩家状态：0-离线、1-在线
@property (nonatomic, readonly) NSInteger status;
/// 自定义玩家状态，开发者可随意设置任何值，意义由开发者自行判断，选填
@property (nonatomic, readonly) NSInteger customStatus;
/// 自定义玩家属性，选填
@property (nonatomic, readonly, copy) NSString * _Nonnull customProperties;
- (nonnull instancetype)initWithId:(NSString * _Nonnull)id status:(NSInteger)status customStatus:(NSInteger)customStatus customProperties:(NSString * _Nonnull)customProperties OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// 用户操作信息（对齐 Unity PlayerInputInfo）
SWIFT_CLASS("_TtC18TapOnlineBattleSDK15PlayerInputInfo")
@interface PlayerInputInfo : NSObject
/// 玩家ID
@property (nonatomic, readonly, copy) NSString * _Nonnull playerId;
/// 玩家操作数据，utf8字符串格式
@property (nonatomic, readonly, copy) NSString * _Nonnull data;
/// 服务器收到该操作数据的时间，1970年开始的毫秒数（JSON key: serverTms）
@property (nonatomic, readonly, copy) NSString * _Nonnull serverTime;
- (nonnull instancetype)initWithPlayerId:(NSString * _Nonnull)playerId data:(NSString * _Nonnull)data serverTime:(NSString * _Nonnull)serverTime OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// 随机数生成器对象（对齐 Unity RandomNumberGenerator）
SWIFT_CLASS("_TtC18TapOnlineBattleSDK21RandomNumberGenerator")
@interface RandomNumberGenerator : NSObject
/// 使用指定种子创建（使用 onFrameSyncStarted 返回的 seed）
- (nonnull instancetype)initWithSeed:(NSInteger)seed OBJC_DESIGNATED_INITIALIZER;
/// 生成 0 ~ 0x7fffffff 之间的随机整数
- (NSInteger)randomInt SWIFT_WARN_UNUSED_RESULT;
/// 释放 native 资源（使用完毕后必须调用；deinit 兜底自动释放）
- (void)free;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// 房间基本信息（用于房间列表）
SWIFT_CLASS("_TtC18TapOnlineBattleSDK13RoomBasicInfo")
@interface RoomBasicInfo : NSObject
/// 房间ID
@property (nonatomic, readonly, copy) NSString * _Nonnull id;
/// 房间名字，选填
@property (nonatomic, readonly, copy) NSString * _Nonnull name;
/// 房间类型
@property (nonatomic, readonly, copy) NSString * _Nonnull type;
/// 房间自定义属性
@property (nonatomic, readonly, copy) NSString * _Nonnull customProperties;
/// 房间最大人数
@property (nonatomic, readonly) NSInteger maxPlayerCount;
/// 房间当前人数
@property (nonatomic, readonly) NSInteger playerCount;
/// 房间创建时间
@property (nonatomic, readonly, copy) NSString * _Nonnull createTime;
- (nonnull instancetype)initWithId:(NSString * _Nonnull)id name:(NSString * _Nonnull)name type:(NSString * _Nonnull)type customProperties:(NSString * _Nonnull)customProperties maxPlayerCount:(NSInteger)maxPlayerCount playerCount:(NSInteger)playerCount createTime:(NSString * _Nonnull)createTime OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// 房间配置
SWIFT_CLASS("_TtC18TapOnlineBattleSDK10RoomConfig")
@interface RoomConfig : NSObject
/// 房间最大支持人数，取值范围为[1, 20]，必填
@property (nonatomic, readonly) NSInteger maxPlayerCount;
/// 房间类型，最大32字节,必填
@property (nonatomic, readonly, copy) NSString * _Nonnull type;
/// 房间匹配参数，选填，最大支持3个K/V对
@property (nonatomic, readonly, copy) NSDictionary<NSString *, NSString *> * _Nonnull matchParams;
/// 房间名称，最大64个字节，选填
@property (nonatomic, readonly, copy) NSString * _Nonnull name;
/// 自定义房间属性，最大2048字节，选填
@property (nonatomic, readonly, copy) NSString * _Nonnull customProperties;
- (nonnull instancetype)initWithMaxPlayerCount:(NSInteger)maxPlayerCount type:(NSString * _Nonnull)type matchParams:(NSDictionary<NSString *, NSString *> * _Nonnull)matchParams name:(NSString * _Nonnull)name customProperties:(NSString * _Nonnull)customProperties OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// 房间信息
SWIFT_CLASS("_TtC18TapOnlineBattleSDK8RoomInfo")
@interface RoomInfo : NSObject
/// 房间ID
@property (nonatomic, readonly, copy) NSString * _Nonnull id;
/// 房间名称，选填
@property (nonatomic, readonly, copy) NSString * _Nonnull name;
/// 房间类型
@property (nonatomic, readonly, copy) NSString * _Nonnull type;
/// 房主ID
@property (nonatomic, readonly, copy) NSString * _Nonnull ownerId;
/// 房间状态，0-未开始，1-进行中（帧同步中），2-已结束，选填
@property (nonatomic, readonly) NSInteger status;
/// 自定义房间属性，选填
@property (nonatomic, readonly, copy) NSString * _Nonnull customProperties;
/// 房间最大支持人数
@property (nonatomic, readonly) NSInteger maxPlayerCount;
/// 房间内当前玩家列表
@property (nonatomic, readonly, copy) NSArray<PlayerInfo *> * _Nonnull players;
/// 房间创建时间，1970年开始的秒数
@property (nonatomic, readonly, copy) NSString * _Nonnull createTime;
- (nonnull instancetype)initWithId:(NSString * _Nonnull)id name:(NSString * _Nonnull)name type:(NSString * _Nonnull)type ownerId:(NSString * _Nonnull)ownerId status:(NSInteger)status customProperties:(NSString * _Nonnull)customProperties maxPlayerCount:(NSInteger)maxPlayerCount players:(NSArray<PlayerInfo *> * _Nonnull)players createTime:(NSString * _Nonnull)createTime OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// 查询房间返回结果（对齐 Unity RoomListData）
SWIFT_CLASS("_TtC18TapOnlineBattleSDK12RoomListData")
@interface RoomListData : NSObject
/// 房间列表
@property (nonatomic, readonly, copy) NSArray<RoomBasicInfo *> * _Nonnull rooms;
/// 用于请求下一页的偏移量
@property (nonatomic, readonly) NSInteger offset;
/// 是否还有更多房间可以拉取
@property (nonatomic, readonly) BOOL hasMore;
- (nonnull instancetype)initWithRooms:(NSArray<RoomBasicInfo *> * _Nonnull)rooms offset:(NSInteger)offset hasMore:(BOOL)hasMore OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// 发送自定义消息回调监听器
SWIFT_PROTOCOL("_TtP18TapOnlineBattleSDK25SendCustomMessageListener_")
@protocol SendCustomMessageListener
- (void)onSuccess;
- (void)onFailureWithError:(ErrorResponse * _Nonnull)error;
@end

/// 发送帧输入回调监听器
SWIFT_PROTOCOL("_TtP18TapOnlineBattleSDK22SendFrameInputListener_")
@protocol SendFrameInputListener
- (void)onSuccess;
- (void)onFailureWithError:(ErrorResponse * _Nonnull)error;
@end

/// 开始帧同步回调监听器
SWIFT_PROTOCOL("_TtP18TapOnlineBattleSDK22StartFrameSyncListener_")
@protocol StartFrameSyncListener
- (void)onSuccess;
- (void)onFailureWithError:(ErrorResponse * _Nonnull)error;
@end

/// 停止帧同步回调监听器
SWIFT_PROTOCOL("_TtP18TapOnlineBattleSDK21StopFrameSyncListener_")
@protocol StopFrameSyncListener
- (void)onSuccess;
- (void)onFailureWithError:(ErrorResponse * _Nonnull)error;
@end

/// 对战通知监听器（对齐 Unity TapOnlineBattleCallback，方法签名改为散字段参数）
/// ⚠️ 线程说明：请求回调和通知回调均在 com.taptap.battle.callback 串行队列执行，
/// 不保证主线程。如需更新 UI，请主动派发到 DispatchQueue.main。
SWIFT_PROTOCOL("_TtP18TapOnlineBattleSDK23TapOnlineBattleCallback_")
@protocol TapOnlineBattleCallback <NSObject>
@optional
/// 与服务端连接断开
- (void)onDisconnectedWithCode:(NSInteger)code msg:(NSString * _Nonnull)msg;
/// 对战服务端异常
- (void)onBattleServiceError;
/// 房间属性变更
- (void)onRoomPropertiesChangedWithId:(NSString * _Nonnull)id name:(NSString * _Nonnull)name customProperties:(NSString * _Nonnull)customProperties;
/// 玩家更新自定义属性
- (void)onPlayerCustomPropertiesChangedWithPlayerId:(NSString * _Nonnull)playerId properties:(NSString * _Nonnull)properties;
/// 玩家更新自定义状态
- (void)onPlayerCustomStatusChangedWithPlayerId:(NSString * _Nonnull)playerId status:(NSInteger)status;
/// 开始帧同步
- (void)onFrameSyncStartedWithFrameSyncInfo:(FrameSyncInfo * _Nonnull)frameSyncInfo;
/// 收到帧同步数据
- (void)onFrameReceivedWithFrameData:(FrameData * _Nonnull)frameData;
/// 停止帧同步
- (void)onFrameSyncStoppedWithRoomId:(NSString * _Nonnull)roomId frameSyncId:(NSInteger)frameSyncId reason:(NSInteger)reason;
/// 玩家离线
- (void)onPlayerOfflineWithRoomId:(NSString * _Nonnull)roomId roomOwnerId:(NSString * _Nonnull)roomOwnerId playerId:(NSString * _Nonnull)playerId;
/// 玩家离开房间
- (void)onPlayerLeftWithRoomId:(NSString * _Nonnull)roomId roomOwnerId:(NSString * _Nonnull)roomOwnerId playerId:(NSString * _Nonnull)playerId;
/// 玩家进入房间
- (void)onPlayerEnteredWithRoomId:(NSString * _Nonnull)roomId playerInfo:(PlayerInfo * _Nonnull)playerInfo;
/// 收到玩家自定义消息
- (void)onCustomMessageReceivedWithPlayerId:(NSString * _Nonnull)playerId msg:(NSString * _Nonnull)msg;
/// 玩家被踢出
- (void)onPlayerKickedWithRoomId:(NSString * _Nonnull)roomId playerId:(NSString * _Nonnull)playerId;
@end

/// 错误码常量（对齐 Unity TapOnlineBattleConstant）
SWIFT_CLASS("_TtC18TapOnlineBattleSDK23TapOnlineBattleConstant")
@interface TapOnlineBattleConstant : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ERROR_INVALID_PARAMS;)
+ (NSInteger)ERROR_INVALID_PARAMS SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ERROR_INIT_INTERNAL_FAILED;)
+ (NSInteger)ERROR_INIT_INTERNAL_FAILED SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ERROR_UNKNOWN;)
+ (NSInteger)ERROR_UNKNOWN SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ERROR_NOT_INIT_OR_LOGIN;)
+ (NSInteger)ERROR_NOT_INIT_OR_LOGIN SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ERROR_NOT_LAUNCHED_BY_TAP_CLIENT;)
+ (NSInteger)ERROR_NOT_LAUNCHED_BY_TAP_CLIENT SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ERROR_SYSTEM_ERROR;)
+ (NSInteger)ERROR_SYSTEM_ERROR SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ERROR_SDK_ERROR;)
+ (NSInteger)ERROR_SDK_ERROR SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ERROR_REQUEST_RATE_LIMIT_EXCEEDED;)
+ (NSInteger)ERROR_REQUEST_RATE_LIMIT_EXCEEDED SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ERROR_MALICIOUS_USER;)
+ (NSInteger)ERROR_MALICIOUS_USER SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ERROR_TOO_MANY_CONNECTIONS;)
+ (NSInteger)ERROR_TOO_MANY_CONNECTIONS SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ERROR_NETWORK_ERROR;)
+ (NSInteger)ERROR_NETWORK_ERROR SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ERROR_INVALID_REQUEST;)
+ (NSInteger)ERROR_INVALID_REQUEST SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ERROR_INVALID_AUTHORIZATION;)
+ (NSInteger)ERROR_INVALID_AUTHORIZATION SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ERROR_UNAUTHORIZED;)
+ (NSInteger)ERROR_UNAUTHORIZED SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ERROR_ALREADY_CONNECTED;)
+ (NSInteger)ERROR_ALREADY_CONNECTED SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ERROR_PREVIOUS_REQUEST_IN_PROGRESS;)
+ (NSInteger)ERROR_PREVIOUS_REQUEST_IN_PROGRESS SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ERROR_UNIMPLEMENTED;)
+ (NSInteger)ERROR_UNIMPLEMENTED SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ERROR_FORBIDDEN;)
+ (NSInteger)ERROR_FORBIDDEN SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ERROR_ROOM_TEMPLATE_NOT_FOUND;)
+ (NSInteger)ERROR_ROOM_TEMPLATE_NOT_FOUND SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ERROR_ROOM_COUNT_LIMIT_EXCEEDED;)
+ (NSInteger)ERROR_ROOM_COUNT_LIMIT_EXCEEDED SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ERROR_NOT_IN_ROOM;)
+ (NSInteger)ERROR_NOT_IN_ROOM SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ERROR_ALREADY_IN_ROOM;)
+ (NSInteger)ERROR_ALREADY_IN_ROOM SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ERROR_NOT_ROOM_OWNER;)
+ (NSInteger)ERROR_NOT_ROOM_OWNER SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ERROR_ROOM_FULL;)
+ (NSInteger)ERROR_ROOM_FULL SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ERROR_ROOM_NOT_EXIST;)
+ (NSInteger)ERROR_ROOM_NOT_EXIST SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ERROR_FRAME_SYNC_NOT_STARTED;)
+ (NSInteger)ERROR_FRAME_SYNC_NOT_STARTED SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ERROR_FRAME_SYNC_ALREADY_STARTED;)
+ (NSInteger)ERROR_FRAME_SYNC_ALREADY_STARTED SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ERROR_FRAME_INPUT_SIZE_LIMIT_EXCEEDED;)
+ (NSInteger)ERROR_FRAME_INPUT_SIZE_LIMIT_EXCEEDED SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ERROR_FRAME_INPUT_COUNT_LIMIT_EXCEEDED;)
+ (NSInteger)ERROR_FRAME_INPUT_COUNT_LIMIT_EXCEEDED SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ERROR_PLAYER_NOT_FOUND;)
+ (NSInteger)ERROR_PLAYER_NOT_FOUND SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// @deprecated 请迁移至 TapTapOnlineBattle
/// 本类保留用于源码级兼容，所有方法转发至 TapTapOnlineBattle。
SWIFT_CLASS_NAMED("TapTapBattleLegacy") SWIFT_DEPRECATED_MSG("请迁移至 TapTapOnlineBattle", "_TtC18TapOnlineBattleSDK18TapTapOnlineBattle")
@interface TapTapBattle : NSObject
+ (void)connectWithListener:(id <ConnectListener> _Nullable)listener SWIFT_DEPRECATED_MSG("", "TapTapOnlineBattle.connect");
+ (void)disconnectWithListener:(id <DisconnectListener> _Nullable)listener SWIFT_DEPRECATED_MSG("", "TapTapOnlineBattle.disconnect");
+ (void)createRoomWithRequest:(CreateRoomConfig * _Nonnull)request listener:(id <CreateRoomListener> _Nullable)listener SWIFT_DEPRECATED_MSG("", "TapTapOnlineBattle.createRoom");
+ (void)matchRoomWithRequest:(MatchRoomConfig * _Nonnull)request listener:(id <MatchRoomListener> _Nullable)listener SWIFT_DEPRECATED_MSG("", "TapTapOnlineBattle.matchRoom");
+ (void)leaveRoomWithListener:(id <LeaveRoomListener> _Nullable)listener SWIFT_DEPRECATED_MSG("", "TapTapOnlineBattle.leaveRoom");
+ (void)startFrameSyncWithListener:(id <StartFrameSyncListener> _Nullable)listener SWIFT_DEPRECATED_MSG("", "TapTapOnlineBattle.startFrameSync");
+ (void)stopFrameSyncWithListener:(id <StopFrameSyncListener> _Nullable)listener SWIFT_DEPRECATED_MSG("", "TapTapOnlineBattle.stopFrameSync");
+ (void)kickRoomPlayerWithPlayerID:(NSString * _Nonnull)playerID listener:(id <KickRoomPlayerListener> _Nullable)listener SWIFT_DEPRECATED_MSG("", "TapTapOnlineBattle.kickRoomPlayer");
+ (void)registerOnlineBattleCallback:(id <TapOnlineBattleCallback> _Nonnull)listener SWIFT_DEPRECATED_MSG("", "TapTapOnlineBattle.registerOnlineBattleCallback");
+ (void)unRegisterOnlineBattleCallback:(id <TapOnlineBattleCallback> _Nonnull)listener SWIFT_DEPRECATED_MSG("", "TapTapOnlineBattle.unRegisterOnlineBattleCallback");
+ (RandomNumberGenerator * _Nonnull)NewRandomNumberGeneratorWithSeed:(NSInteger)seed SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_MSG("", "TapTapOnlineBattle.NewRandomNumberGenerator");
+ (void)setLogLevelWithLevel:(NSInteger)level logToConsole:(BOOL)logToConsole SWIFT_DEPRECATED_MSG("", "TapTapOnlineBattle.setLogLevel");
+ (NSString * _Nullable)getVersion SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_MSG("", "TapTapOnlineBattle.getVersion");
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@protocol UpdatePlayerCustomStatusListener;
@protocol UpdatePlayerCustomPropertiesListener;
@protocol UpdateRoomPropertiesListener;
/// TapTap Battle SDK Public API
/// 提供对战服务功能，包括房间管理、帧同步对战等。
/// Native 库 (onlinebattle_sdk.xcframework) 在 TapSDK 初始化时自动加载。
SWIFT_CLASS("_TtC18TapOnlineBattleSDK18TapTapOnlineBattle")
@interface TapTapOnlineBattle : NSObject
/// SDK 包装层版本（由 CI bump 流程统一维护，与 podspec 版本对齐）
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull Version;)
+ (NSString * _Nonnull)Version SWIFT_WARN_UNUSED_RESULT;
+ (void)connectWithListener:(id <ConnectListener> _Nullable)listener;
+ (void)disconnectWithListener:(id <DisconnectListener> _Nullable)listener;
/// 创建房间
+ (void)createRoomWithRequest:(CreateRoomConfig * _Nonnull)request listener:(id <CreateRoomListener> _Nullable)listener;
/// 匹配房间（匹配不到时自动创建）
+ (void)matchRoomWithRequest:(MatchRoomConfig * _Nonnull)request listener:(id <MatchRoomListener> _Nullable)listener;
/// 获取房间列表
/// \param roomType 房间类型，不填则拉取全部类型
///
/// \param offset 偏移量，默认为 0
///
/// \param limit 获取数量，默认为 20，最大 100
///
+ (void)getRoomListWithRoomType:(NSString * _Nonnull)roomType offset:(NSInteger)offset limit:(NSInteger)limit listener:(id <GetRoomListListener> _Nullable)listener;
/// 加入房间
/// \param roomId 房间ID
///
/// \param playerConfig 玩家配置，选填
///
+ (void)joinRoomWithRoomId:(NSString * _Nonnull)roomId playerConfig:(PlayerConfig * _Nonnull)playerConfig listener:(id <JoinRoomListener> _Nullable)listener;
/// 离开房间
+ (void)leaveRoomWithListener:(id <LeaveRoomListener> _Nullable)listener;
/// 更新玩家自定义状态
+ (void)updatePlayerCustomStatusWithStatus:(NSInteger)status listener:(id <UpdatePlayerCustomStatusListener> _Nullable)listener;
/// 更新玩家自定义属性
+ (void)updatePlayerCustomPropertiesWithProperties:(NSString * _Nonnull)properties listener:(id <UpdatePlayerCustomPropertiesListener> _Nullable)listener;
/// 更新房间属性（仅限房主调用）
/// \param roomName 房间名称
///
/// \param properties 房间自定义属性，最大 2048 字节
///
+ (void)updateRoomPropertiesWithRoomName:(NSString * _Nonnull)roomName properties:(NSString * _Nonnull)properties listener:(id <UpdateRoomPropertiesListener> _Nullable)listener;
+ (void)startFrameSyncWithListener:(id <StartFrameSyncListener> _Nullable)listener;
/// 发送玩家帧输入，同一帧允许发送多次操作，无需等待回调
/// \param data 游戏操作，utf8字符串格式，最大 1024 字节
///
+ (void)sendFrameInputWithData:(NSString * _Nonnull)data listener:(id <SendFrameInputListener> _Nullable)listener;
+ (void)stopFrameSyncWithListener:(id <StopFrameSyncListener> _Nullable)listener;
+ (void)kickRoomPlayerWithPlayerID:(NSString * _Nonnull)playerID listener:(id <KickRoomPlayerListener> _Nullable)listener;
/// 发送自定义消息，每秒允许调用 20 次，无需等待回调
/// \param msg 消息内容，utf8字符串，最大 2048 字节
///
/// \param type 接收者类型：0 房间所有玩家（不含发送者），1 指定玩家
///
/// \param receivers type==1 时有效，最多 20 个ID
///
+ (void)sendCustomMessageWithMsg:(NSString * _Nonnull)msg type:(NSInteger)type receivers:(NSArray<NSString *> * _Nonnull)receivers listener:(id <SendCustomMessageListener> _Nullable)listener;
/// 创建随机数生成器对象（对齐 Unity NewRandomNumberGenerator）
/// 使用 onFrameSyncStarted 返回的 seed，保证所有玩家随机序列一致
+ (RandomNumberGenerator * _Nonnull)NewRandomNumberGeneratorWithSeed:(NSInteger)seed SWIFT_WARN_UNUSED_RESULT;
+ (void)initializeSDK;
+ (void)setLogLevelWithLevel:(NSInteger)level logToConsole:(BOOL)logToConsole;
+ (NSString * _Nullable)getVersion SWIFT_WARN_UNUSED_RESULT;
/// 注册对战通知监听器
+ (void)registerOnlineBattleCallback:(id <TapOnlineBattleCallback> _Nonnull)listener;
/// 注销对战通知监听器
+ (void)unRegisterOnlineBattleCallback:(id <TapOnlineBattleCallback> _Nonnull)listener;
+ (void)ensureInitialization;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// 更新玩家自定义属性回调监听器
SWIFT_PROTOCOL("_TtP18TapOnlineBattleSDK36UpdatePlayerCustomPropertiesListener_")
@protocol UpdatePlayerCustomPropertiesListener
- (void)onSuccess;
- (void)onFailureWithError:(ErrorResponse * _Nonnull)error;
@end

/// 更新玩家自定义状态回调监听器
SWIFT_PROTOCOL("_TtP18TapOnlineBattleSDK32UpdatePlayerCustomStatusListener_")
@protocol UpdatePlayerCustomStatusListener
- (void)onSuccess;
- (void)onFailureWithError:(ErrorResponse * _Nonnull)error;
@end

/// 更新房间属性回调监听器
SWIFT_PROTOCOL("_TtP18TapOnlineBattleSDK28UpdateRoomPropertiesListener_")
@protocol UpdateRoomPropertiesListener
- (void)onSuccess;
- (void)onFailureWithError:(ErrorResponse * _Nonnull)error;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
